server:
  port: 8080
spring:
  application:
    name: springboot-artificial-intelligence
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4-turbo
rag:
  aiapp:
    vectorStorePath: ../vectorStore.json
    documentsToLoad:
      - classpath:/movies500.csv
ninja-api:
  api-url: https://api.api-ninjas.com/v1/celebrity
  api-key: ${NINJA_API_KEY}